name: Metrics
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  github-metrics:
    runs-on: ubuntu-24.04
    environment:
      name: PAT
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          #### Base settings ####
          filename: metrics.classic.svg
          token: ${{ secrets.PAT }}
          base: header, repositories, activity, community, metadata
          base_indepth: yes
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Europe/Moscow
          config_display: regular
          output_action: commit
          committer_message: "chore: update metrics"
          #### Plugin settings ####
          #Lines plugin
          plugin_lines: yes
          plugin_lines_sections: base
          #Activity plugin
          plugin_activity: yes
          #Habits plugin
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          #Introduction plugin
          plugin_introduction: yes
          plugin_introduction_title: yes
          #Languages plugin
          plugin_languages: yes
          plugin_languages_indepth: true
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15