name: Metrics
on:
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-24.04
    environment:
      name: PAT
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          #### Base settings ####
          filename: metrics.classic.svg
          token: ${{ secrets.PAT }}
          base: header, repositories, activity, community
          base_indepth: yes
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Europe/Moscow
          config_display: regular
          output_action: commit
          users_ignored:
          committer_message: "chore: update metrics"
          #### Plugin settings ####
          #Lines plugin
          plugin_lines: yes
          plugin_lines_sections: base
          #Habits plugin
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_trim: yes
          plugin_habits_languages_limit: 0
          #Introduction plugin
          plugin_introduction: yes
          plugin_introduction_title: yes
          #Languages plugin
          plugin_languages: yes
          plugin_languages_ignored: xml, svg, sql, gradle, json, text, swift, ini, markdown, TOML, browserslist, cmake, Microsoft Visual Studio Solution, XML Propery List
          plugin_languages_limit: 0
          plugin_languages_indepth: yes
          plugin_languages_other: no
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365
